name: Deploy
on:
  push:

env:
  PROJECT_ID: '231388685322'
  GAR_LOCATION: 'us-east1'
  REPOSITORY: 'zah'

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'zah-website'
        workload_identity_provider: 'projects/231388685322/locations/global/workloadIdentityPools/zah-github/providers/zah-github-provider'

    - name: 'set up cloud sdk'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'login to artifact registry'
      uses: 'docker/login-action@v1'
      with:
        registry: 'us-east1-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Build and push Container'
      run: |-
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/zah:test" ./
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/zah:test"
