name: Deploy
on:
  push:

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'zah-website'
        workload_identity_provider: 'projects/231388685322/locations/global/workloadIdentityPools/zah-github/providers/zah-github-provider'

    - name: 'set up cloud sdk'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'use gcloud CLI'
      run: 'gcloud info'
